# https://www.gitpod.io/docs/config-gitpod-file

ports:
  - port: 3000
    onOpen: notify

tasks:
  - init: npm install
    command: npm run build && npm run dev

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
